name: CI - Windows Python 3.11

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-and-smoke:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Smoke test imports
        run: |
          python - <<'PY'
          import importlib
          names = ['numpy','torch','transformers','librosa','numba']
          for n in names:
              try:
                  m = importlib.import_module(n)
                  print(n, getattr(m,'__version__','unknown'))
              except Exception as e:
                  print('IMPORT-ERROR', n, e)
                  raise
          PY
